---
name: spyns
channels:
  - defaults
  - jkglasbrenner
  - matsci
dependencies:
  - anaconda=5.3.0=py37_0
  - autopep8
  - enumlib
  - pyhamcrest
  - pytest-runner
  - sphinx_rtd_theme
  - yapf
  - pip:
    - flake8
    - pip==18.1
    - pydocstyle
    - pymatgen
    - sphinx-autodoc-typehints
...
